server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  dataSource:
    url: jdbc:mysql://localhost:3306/zyp_datebase?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    register-with-eureka: true  # 是否将自己注册进EurekaServer默认为true
    # 是否从 EurekaServer 中抓取已有的注册信息， 默认为true，
    # 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 设 置 与 eureka server 交互的地址 查询 服 务 和注 册 服 务 都需要依 赖这个 地址
      defaultZone : http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
      #defaultZone : http://eureka7001.com:7001/eureka/
  instance:
    instance-id: pay8001
    prefer-ip-address: true
    # 默认30，现在改成1（Eureka客户端向服务端发送心跳的时间间隔，单位为秒， 默认是30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务器在收到最后一次新题哦啊后等待时间上限，单位为秒（默认90秒）， 超时将会剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml;;;zypppppppppppppppppp
  type-aliases-package: com.atguigu.springcloud.entity
